### ISSUE TITLE
Hi Chuvisco

### ISSUE THREAD

**Issue by shanksf** [Chuvisco88/Chuvisco_CatalogRuleFix#1]
It works only two days, why? I use magento 1.9.2.0

**Comment by Chuvisco88** [comment]
I did not have this issue so far. How did you set up your cron jobs?

**Comment by shanksf** [comment]
I don't know how to set up cron jobs, I am new to magento

**Comment by Chuvisco88** [comment]
Closed, as documentation on how to set up cron jobs are linked in the README.
Please open a new issue, if you have your cron jobs configured and it still does not work
